apiVersion: coralogix.com/v1beta1
kind: Alert
metadata:
  labels:
    app.kubernetes.io/name: alert
    app.kubernetes.io/instance: alert-sample
    app.kubernetes.io/part-of: coralogix-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: coralogix-operator
  name: metric-threshold
spec:
  items:
    - name: http-error-rate
      description: Alert when HTTP 5xx rate exceeds 10/min
      runbook: https://example.com/runbook
      expression: sum(rate(http_requests_total{status=~"5.."}[1m]))
      labels:
        severity: high
      annotations:
        alert_owner: platform
      conditions:
        - operator: GreaterThan
          severity: critical
          duration: 5m
          value: "10"
      platform:
        kind: coralogix
        settings:
          severity: critical
          replaceWithZero: false
          minDataCoveragePercent: 80
          minNonNullValuesPct: 100
          triggeredOnUndetectedValues: false
          skipCxEnvIdLabelEnforcement: false
