apiVersion: coralogix.com/v1beta1
kind: Alert
metadata:
  labels:
    app.kubernetes.io/name: alert
    app.kubernetes.io/instance: alert-sample
    app.kubernetes.io/part-of: coralogix-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: coralogix-operator
  name: metric-threshold
spec:
  items:
    - name: metric-threshold
      description: Check the platform-data-prometheus Prometheus pods in the observability namespace, confirm they are running and ready, review recent restarts/events, and validate that the jobs targets are reachable and successfully scraped. The alert should clear once at least 2 targets are back up.
      annotations: {}
      labels: {}
      enabled: true
      platform:
        kind: coralogix
        settings:
          replaceWithZero: false
          triggeredOnUndetectedValues: false
          notificationGroups: []
          minDataCoveragePercent: 100
          minNonNullValuesPct: 100
          skipCxEnvIdLabelEnforcement: false
      expression: |-
        sum by (job) (
          up{container="prometheus",job=~"platform-data-prometheus-prometheus",namespace="observability"}
        )
      runbook: https://github.com/coralogix/eng-observability/blob/master/metrics/prom/docs/runbooks/PrometheusClusterIsDown.md
      conditions:
        - operator: LessThan
          severity: warning
          duration: 15m
          value: '2.0'
